#!/usr/bin/env bash
# Script that displays FizzBuzz numbers from 1 to 100.
for var in {1..100}
do
	if [ $(( var%5 )) -eq 0 ] && [ $(( var%3 )) -eq 0 ];then
	   echo "FizzBuzz"
	elif [ $(( var%3 )) -eq 0 ];then
	     echo "Fizz"
	elif [ $(( var%5 )) -eq 0 ];then
	     echo "Buzz"
	else
	     echo "$var"
	fi
done
