#!/usr/bin/env bash
# Script that loops from 1 to 10 and display
# bad luck for 4th iteration
# god luck for 8th iteration
# otherwise print Holberton School
i=1
while [[ "$i" -le 10 ]]
do
	if [[ "$i" -eq 4 ]]
	then
		echo "bad luck"
	elif [[ "$i" -eq 8 ]]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
done