#!/usr/bin/env bash
# Advance script that runs nginx server as nginx user using 7 lines or less.
pkill -1 apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start